DROP TABLE IF EXISTS megasoft.project_worker CASCADE;
DROP TABLE IF EXISTS megasoft.project CASCADE;
DROP TABLE IF EXISTS megasoft.client CASCADE;
DROP TABLE IF EXISTS megasoft.worker CASCADE;
DROP SCHEMA IF EXISTS megasoft;

CREATE SCHEMA megasoft;

CREATE TABLE megasoft.worker (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL CHECK (LENGTH(NAME) >= 2 AND LENGTH(NAME) <= 1000),
    BIRTHDAY DATE CHECK (YEAR(BIRTHDAY) > 1900),
    LEVEL ENUM('Trainee', 'Junior', 'Middle', 'Senior') NOT NULL,
    SALARY INT CHECK (SALARY >= 100 AND SALARY <= 100000)
);

CREATE TABLE megasoft.client (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(1000) NOT NULL CHECK (LENGTH(NAME) >= 2 AND LENGTH(NAME) <= 1000)
);

CREATE TABLE megasoft.project (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CLIENT_ID INT,
    START_DATE DATE,
    FINISH_DATE DATE,
    FOREIGN KEY (CLIENT_ID) REFERENCES megasoft.client(ID) ON DELETE CASCADE
);

CREATE TABLE megasoft.project_worker (
    PROJECT_ID INT,
    WORKER_ID INT,
    PRIMARY KEY (PROJECT_ID, WORKER_ID),
    FOREIGN KEY (PROJECT_ID) REFERENCES megasoft.project(ID) ON DELETE CASCADE,
    FOREIGN KEY (WORKER_ID) REFERENCES megasoft.worker(ID) ON DELETE CASCADE
);
